// Copyright (c) YugaByte, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License
// is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
// or implied.  See the License for the specific language governing permissions and limitations
// under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: yb/common/common_net.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HostPortPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host *string `protobuf:"bytes,1,req,name=host" json:"host,omitempty"`
	Port *uint32 `protobuf:"varint,2,req,name=port" json:"port,omitempty"`
}

func (x *HostPortPB) Reset() {
	*x = HostPortPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yb_common_common_net_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostPortPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostPortPB) ProtoMessage() {}

func (x *HostPortPB) ProtoReflect() protoreflect.Message {
	mi := &file_yb_common_common_net_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostPortPB.ProtoReflect.Descriptor instead.
func (*HostPortPB) Descriptor() ([]byte, []int) {
	return file_yb_common_common_net_proto_rawDescGZIP(), []int{0}
}

func (x *HostPortPB) GetHost() string {
	if x != nil && x.Host != nil {
		return *x.Host
	}
	return ""
}

func (x *HostPortPB) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

type CloudInfoPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlacementCloud  *string `protobuf:"bytes,1,opt,name=placement_cloud,json=placementCloud" json:"placement_cloud,omitempty"`
	PlacementRegion *string `protobuf:"bytes,2,opt,name=placement_region,json=placementRegion" json:"placement_region,omitempty"`
	PlacementZone   *string `protobuf:"bytes,3,opt,name=placement_zone,json=placementZone" json:"placement_zone,omitempty"`
}

func (x *CloudInfoPB) Reset() {
	*x = CloudInfoPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yb_common_common_net_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloudInfoPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudInfoPB) ProtoMessage() {}

func (x *CloudInfoPB) ProtoReflect() protoreflect.Message {
	mi := &file_yb_common_common_net_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudInfoPB.ProtoReflect.Descriptor instead.
func (*CloudInfoPB) Descriptor() ([]byte, []int) {
	return file_yb_common_common_net_proto_rawDescGZIP(), []int{1}
}

func (x *CloudInfoPB) GetPlacementCloud() string {
	if x != nil && x.PlacementCloud != nil {
		return *x.PlacementCloud
	}
	return ""
}

func (x *CloudInfoPB) GetPlacementRegion() string {
	if x != nil && x.PlacementRegion != nil {
		return *x.PlacementRegion
	}
	return ""
}

func (x *CloudInfoPB) GetPlacementZone() string {
	if x != nil && x.PlacementZone != nil {
		return *x.PlacementZone
	}
	return ""
}

var File_yb_common_common_net_proto protoreflect.FileDescriptor

var file_yb_common_common_net_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x79, 0x62, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x5f, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x79, 0x62,
	0x22, 0x34, 0x0a, 0x0a, 0x48, 0x6f, 0x73, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x50, 0x42, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d,
	0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x88, 0x01, 0x0a, 0x0b, 0x43, 0x6c, 0x6f, 0x75, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x50, 0x42, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x12,
	0x29, 0x0a, 0x10, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5a, 0x6f, 0x6e,
	0x65, 0x42, 0x08, 0x0a, 0x06, 0x6f, 0x72, 0x67, 0x2e, 0x79, 0x62,
}

var (
	file_yb_common_common_net_proto_rawDescOnce sync.Once
	file_yb_common_common_net_proto_rawDescData = file_yb_common_common_net_proto_rawDesc
)

func file_yb_common_common_net_proto_rawDescGZIP() []byte {
	file_yb_common_common_net_proto_rawDescOnce.Do(func() {
		file_yb_common_common_net_proto_rawDescData = protoimpl.X.CompressGZIP(file_yb_common_common_net_proto_rawDescData)
	})
	return file_yb_common_common_net_proto_rawDescData
}

var file_yb_common_common_net_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_yb_common_common_net_proto_goTypes = []interface{}{
	(*HostPortPB)(nil),  // 0: yb.HostPortPB
	(*CloudInfoPB)(nil), // 1: yb.CloudInfoPB
}
var file_yb_common_common_net_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_yb_common_common_net_proto_init() }
func file_yb_common_common_net_proto_init() {
	if File_yb_common_common_net_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_yb_common_common_net_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostPortPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yb_common_common_net_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloudInfoPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_yb_common_common_net_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yb_common_common_net_proto_goTypes,
		DependencyIndexes: file_yb_common_common_net_proto_depIdxs,
		MessageInfos:      file_yb_common_common_net_proto_msgTypes,
	}.Build()
	File_yb_common_common_net_proto = out.File
	file_yb_common_common_net_proto_rawDesc = nil
	file_yb_common_common_net_proto_goTypes = nil
	file_yb_common_common_net_proto_depIdxs = nil
}
