// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: yb/master/master_backup.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MasterBackupClient is the client API for MasterBackup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MasterBackupClient interface {
	// Client->Master RPCs
	CreateSnapshot(ctx context.Context, in *CreateSnapshotRequestPB, opts ...grpc.CallOption) (*CreateSnapshotResponsePB, error)
	ListSnapshots(ctx context.Context, in *ListSnapshotsRequestPB, opts ...grpc.CallOption) (*ListSnapshotsResponsePB, error)
	ListSnapshotRestorations(ctx context.Context, in *ListSnapshotRestorationsRequestPB, opts ...grpc.CallOption) (*ListSnapshotRestorationsResponsePB, error)
	RestoreSnapshot(ctx context.Context, in *RestoreSnapshotRequestPB, opts ...grpc.CallOption) (*RestoreSnapshotResponsePB, error)
	DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequestPB, opts ...grpc.CallOption) (*DeleteSnapshotResponsePB, error)
	ImportSnapshotMeta(ctx context.Context, in *ImportSnapshotMetaRequestPB, opts ...grpc.CallOption) (*ImportSnapshotMetaResponsePB, error)
	CreateSnapshotSchedule(ctx context.Context, in *CreateSnapshotScheduleRequestPB, opts ...grpc.CallOption) (*CreateSnapshotScheduleResponsePB, error)
	ListSnapshotSchedules(ctx context.Context, in *ListSnapshotSchedulesRequestPB, opts ...grpc.CallOption) (*ListSnapshotSchedulesResponsePB, error)
	DeleteSnapshotSchedule(ctx context.Context, in *DeleteSnapshotScheduleRequestPB, opts ...grpc.CallOption) (*DeleteSnapshotScheduleResponsePB, error)
}

type masterBackupClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterBackupClient(cc grpc.ClientConnInterface) MasterBackupClient {
	return &masterBackupClient{cc}
}

func (c *masterBackupClient) CreateSnapshot(ctx context.Context, in *CreateSnapshotRequestPB, opts ...grpc.CallOption) (*CreateSnapshotResponsePB, error) {
	out := new(CreateSnapshotResponsePB)
	err := c.cc.Invoke(ctx, "/yb.master.MasterBackup/CreateSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterBackupClient) ListSnapshots(ctx context.Context, in *ListSnapshotsRequestPB, opts ...grpc.CallOption) (*ListSnapshotsResponsePB, error) {
	out := new(ListSnapshotsResponsePB)
	err := c.cc.Invoke(ctx, "/yb.master.MasterBackup/ListSnapshots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterBackupClient) ListSnapshotRestorations(ctx context.Context, in *ListSnapshotRestorationsRequestPB, opts ...grpc.CallOption) (*ListSnapshotRestorationsResponsePB, error) {
	out := new(ListSnapshotRestorationsResponsePB)
	err := c.cc.Invoke(ctx, "/yb.master.MasterBackup/ListSnapshotRestorations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterBackupClient) RestoreSnapshot(ctx context.Context, in *RestoreSnapshotRequestPB, opts ...grpc.CallOption) (*RestoreSnapshotResponsePB, error) {
	out := new(RestoreSnapshotResponsePB)
	err := c.cc.Invoke(ctx, "/yb.master.MasterBackup/RestoreSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterBackupClient) DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequestPB, opts ...grpc.CallOption) (*DeleteSnapshotResponsePB, error) {
	out := new(DeleteSnapshotResponsePB)
	err := c.cc.Invoke(ctx, "/yb.master.MasterBackup/DeleteSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterBackupClient) ImportSnapshotMeta(ctx context.Context, in *ImportSnapshotMetaRequestPB, opts ...grpc.CallOption) (*ImportSnapshotMetaResponsePB, error) {
	out := new(ImportSnapshotMetaResponsePB)
	err := c.cc.Invoke(ctx, "/yb.master.MasterBackup/ImportSnapshotMeta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterBackupClient) CreateSnapshotSchedule(ctx context.Context, in *CreateSnapshotScheduleRequestPB, opts ...grpc.CallOption) (*CreateSnapshotScheduleResponsePB, error) {
	out := new(CreateSnapshotScheduleResponsePB)
	err := c.cc.Invoke(ctx, "/yb.master.MasterBackup/CreateSnapshotSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterBackupClient) ListSnapshotSchedules(ctx context.Context, in *ListSnapshotSchedulesRequestPB, opts ...grpc.CallOption) (*ListSnapshotSchedulesResponsePB, error) {
	out := new(ListSnapshotSchedulesResponsePB)
	err := c.cc.Invoke(ctx, "/yb.master.MasterBackup/ListSnapshotSchedules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterBackupClient) DeleteSnapshotSchedule(ctx context.Context, in *DeleteSnapshotScheduleRequestPB, opts ...grpc.CallOption) (*DeleteSnapshotScheduleResponsePB, error) {
	out := new(DeleteSnapshotScheduleResponsePB)
	err := c.cc.Invoke(ctx, "/yb.master.MasterBackup/DeleteSnapshotSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterBackupServer is the server API for MasterBackup service.
// All implementations should embed UnimplementedMasterBackupServer
// for forward compatibility
type MasterBackupServer interface {
	// Client->Master RPCs
	CreateSnapshot(context.Context, *CreateSnapshotRequestPB) (*CreateSnapshotResponsePB, error)
	ListSnapshots(context.Context, *ListSnapshotsRequestPB) (*ListSnapshotsResponsePB, error)
	ListSnapshotRestorations(context.Context, *ListSnapshotRestorationsRequestPB) (*ListSnapshotRestorationsResponsePB, error)
	RestoreSnapshot(context.Context, *RestoreSnapshotRequestPB) (*RestoreSnapshotResponsePB, error)
	DeleteSnapshot(context.Context, *DeleteSnapshotRequestPB) (*DeleteSnapshotResponsePB, error)
	ImportSnapshotMeta(context.Context, *ImportSnapshotMetaRequestPB) (*ImportSnapshotMetaResponsePB, error)
	CreateSnapshotSchedule(context.Context, *CreateSnapshotScheduleRequestPB) (*CreateSnapshotScheduleResponsePB, error)
	ListSnapshotSchedules(context.Context, *ListSnapshotSchedulesRequestPB) (*ListSnapshotSchedulesResponsePB, error)
	DeleteSnapshotSchedule(context.Context, *DeleteSnapshotScheduleRequestPB) (*DeleteSnapshotScheduleResponsePB, error)
}

// UnimplementedMasterBackupServer should be embedded to have forward compatible implementations.
type UnimplementedMasterBackupServer struct {
}

func (UnimplementedMasterBackupServer) CreateSnapshot(context.Context, *CreateSnapshotRequestPB) (*CreateSnapshotResponsePB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSnapshot not implemented")
}
func (UnimplementedMasterBackupServer) ListSnapshots(context.Context, *ListSnapshotsRequestPB) (*ListSnapshotsResponsePB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSnapshots not implemented")
}
func (UnimplementedMasterBackupServer) ListSnapshotRestorations(context.Context, *ListSnapshotRestorationsRequestPB) (*ListSnapshotRestorationsResponsePB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSnapshotRestorations not implemented")
}
func (UnimplementedMasterBackupServer) RestoreSnapshot(context.Context, *RestoreSnapshotRequestPB) (*RestoreSnapshotResponsePB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreSnapshot not implemented")
}
func (UnimplementedMasterBackupServer) DeleteSnapshot(context.Context, *DeleteSnapshotRequestPB) (*DeleteSnapshotResponsePB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSnapshot not implemented")
}
func (UnimplementedMasterBackupServer) ImportSnapshotMeta(context.Context, *ImportSnapshotMetaRequestPB) (*ImportSnapshotMetaResponsePB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportSnapshotMeta not implemented")
}
func (UnimplementedMasterBackupServer) CreateSnapshotSchedule(context.Context, *CreateSnapshotScheduleRequestPB) (*CreateSnapshotScheduleResponsePB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSnapshotSchedule not implemented")
}
func (UnimplementedMasterBackupServer) ListSnapshotSchedules(context.Context, *ListSnapshotSchedulesRequestPB) (*ListSnapshotSchedulesResponsePB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSnapshotSchedules not implemented")
}
func (UnimplementedMasterBackupServer) DeleteSnapshotSchedule(context.Context, *DeleteSnapshotScheduleRequestPB) (*DeleteSnapshotScheduleResponsePB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSnapshotSchedule not implemented")
}

// UnsafeMasterBackupServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterBackupServer will
// result in compilation errors.
type UnsafeMasterBackupServer interface {
	mustEmbedUnimplementedMasterBackupServer()
}

func RegisterMasterBackupServer(s grpc.ServiceRegistrar, srv MasterBackupServer) {
	s.RegisterService(&MasterBackup_ServiceDesc, srv)
}

func _MasterBackup_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnapshotRequestPB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterBackupServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yb.master.MasterBackup/CreateSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterBackupServer).CreateSnapshot(ctx, req.(*CreateSnapshotRequestPB))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterBackup_ListSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotsRequestPB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterBackupServer).ListSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yb.master.MasterBackup/ListSnapshots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterBackupServer).ListSnapshots(ctx, req.(*ListSnapshotsRequestPB))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterBackup_ListSnapshotRestorations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotRestorationsRequestPB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterBackupServer).ListSnapshotRestorations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yb.master.MasterBackup/ListSnapshotRestorations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterBackupServer).ListSnapshotRestorations(ctx, req.(*ListSnapshotRestorationsRequestPB))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterBackup_RestoreSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreSnapshotRequestPB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterBackupServer).RestoreSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yb.master.MasterBackup/RestoreSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterBackupServer).RestoreSnapshot(ctx, req.(*RestoreSnapshotRequestPB))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterBackup_DeleteSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSnapshotRequestPB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterBackupServer).DeleteSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yb.master.MasterBackup/DeleteSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterBackupServer).DeleteSnapshot(ctx, req.(*DeleteSnapshotRequestPB))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterBackup_ImportSnapshotMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportSnapshotMetaRequestPB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterBackupServer).ImportSnapshotMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yb.master.MasterBackup/ImportSnapshotMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterBackupServer).ImportSnapshotMeta(ctx, req.(*ImportSnapshotMetaRequestPB))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterBackup_CreateSnapshotSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnapshotScheduleRequestPB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterBackupServer).CreateSnapshotSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yb.master.MasterBackup/CreateSnapshotSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterBackupServer).CreateSnapshotSchedule(ctx, req.(*CreateSnapshotScheduleRequestPB))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterBackup_ListSnapshotSchedules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotSchedulesRequestPB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterBackupServer).ListSnapshotSchedules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yb.master.MasterBackup/ListSnapshotSchedules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterBackupServer).ListSnapshotSchedules(ctx, req.(*ListSnapshotSchedulesRequestPB))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterBackup_DeleteSnapshotSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSnapshotScheduleRequestPB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterBackupServer).DeleteSnapshotSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yb.master.MasterBackup/DeleteSnapshotSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterBackupServer).DeleteSnapshotSchedule(ctx, req.(*DeleteSnapshotScheduleRequestPB))
	}
	return interceptor(ctx, in, info, handler)
}

// MasterBackup_ServiceDesc is the grpc.ServiceDesc for MasterBackup service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MasterBackup_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yb.master.MasterBackup",
	HandlerType: (*MasterBackupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSnapshot",
			Handler:    _MasterBackup_CreateSnapshot_Handler,
		},
		{
			MethodName: "ListSnapshots",
			Handler:    _MasterBackup_ListSnapshots_Handler,
		},
		{
			MethodName: "ListSnapshotRestorations",
			Handler:    _MasterBackup_ListSnapshotRestorations_Handler,
		},
		{
			MethodName: "RestoreSnapshot",
			Handler:    _MasterBackup_RestoreSnapshot_Handler,
		},
		{
			MethodName: "DeleteSnapshot",
			Handler:    _MasterBackup_DeleteSnapshot_Handler,
		},
		{
			MethodName: "ImportSnapshotMeta",
			Handler:    _MasterBackup_ImportSnapshotMeta_Handler,
		},
		{
			MethodName: "CreateSnapshotSchedule",
			Handler:    _MasterBackup_CreateSnapshotSchedule_Handler,
		},
		{
			MethodName: "ListSnapshotSchedules",
			Handler:    _MasterBackup_ListSnapshotSchedules_Handler,
		},
		{
			MethodName: "DeleteSnapshotSchedule",
			Handler:    _MasterBackup_DeleteSnapshotSchedule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "yb/master/master_backup.proto",
}
