// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: yb/yql/cql/cqlserver/cql_service.proto

package cqlserver

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CQLServerServiceClient is the client API for CQLServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CQLServerServiceClient interface {
}

type cQLServerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCQLServerServiceClient(cc grpc.ClientConnInterface) CQLServerServiceClient {
	return &cQLServerServiceClient{cc}
}

// CQLServerServiceServer is the server API for CQLServerService service.
// All implementations should embed UnimplementedCQLServerServiceServer
// for forward compatibility
type CQLServerServiceServer interface {
}

// UnimplementedCQLServerServiceServer should be embedded to have forward compatible implementations.
type UnimplementedCQLServerServiceServer struct {
}

// UnsafeCQLServerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CQLServerServiceServer will
// result in compilation errors.
type UnsafeCQLServerServiceServer interface {
	mustEmbedUnimplementedCQLServerServiceServer()
}

func RegisterCQLServerServiceServer(s grpc.ServiceRegistrar, srv CQLServerServiceServer) {
	s.RegisterService(&CQLServerService_ServiceDesc, srv)
}

// CQLServerService_ServiceDesc is the grpc.ServiceDesc for CQLServerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CQLServerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yb.cqlserver.CQLServerService",
	HandlerType: (*CQLServerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "yb/yql/cql/cqlserver/cql_service.proto",
}
